name       : usbguard
version    : 1.0.0
release    : 1
source     :
    - https://github.com/USBGuard/usbguard/releases/download/usbguard-1.0.0/usbguard-1.0.0.tar.gz : 5617986cd5dd1a2d311041648a1977d836cf4e33a4121d7f82599f21496abc42
license    : GPL-2.0-only
component  : security
summary    : USBGuard maintains whitelist and blacklist of USB devices to allow better control over what devices are allowed and what aren't in the system
description: |
    USBGuard is a software framework for implementing USB device authorization policies (what kind of USB devices are authorized) as well as method of use policies (how a USB device may interact with the system). Simply put, it is a USB device allowlisting tool.
builddeps  :
    - pkgconfig(libcap-ng)
    - pkgconfig(libqb)
    - pkgconfig(libseccomp)
    - pkgconfig(libsodium)
    - pkgconfig(protobuf)
    - asciidoc
setup      : |
    %configure --with-bundled-catch --with-bundled-pegtl --with-crypto-library=sodium --enable-systemd
build      : |
    %make
install    : |
    %make_install
    rm -f $installdir/usr/lib64/libusbguard.a
check      : |
    %make check
